applications/departamento/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "departamento_app"

urlpatterns = [
    path('new-departamento/',views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
    path('list-departamentos/',views.DepartamentoListView.as_view(), name='listar_departamentos'),
]

applications/empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "empleado_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
        ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
        ),
    path('listar-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
        ),
    path('lista-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
        ),
    path('listar-by-job/<job>/', views.ListByJobEmpleado.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='detalle_empleado'),
    path('add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'
        ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
        ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
        ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamento/models.py
from django.db import models

# Create your models here.

class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    shor_name = models.CharField('Nombre Corto', max_length=20, unique = True)
    anulate = models.BooleanField('Anulado', default = False)

    class Meta:
        verbose_name = 'Mi Departamento'
        verbose_name_plural = 'Areas de la empresa'
        ordering = ['name']
        unique_together = ('name','shor_name')

    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.shor_name 

applications/departamento/forms.py
from django import forms

class NewDepartamentoForm(forms.Form):
    nombre = forms.CharField(max_length=50, required=True)
    apellidos = forms.CharField(max_length=50, required=True)
    departamento = forms.CharField(max_length=50, required=True)
    shorname = forms.CharField(max_length=20, required=True)

applications/departamento/views.py
from django.shortcuts import render
from django.views.generic.edit import (
    FormView,
)
from django.views.generic import(
    ListView,
)

from .forms import NewDepartamentoForm
from applications.empleados.models import Empleado
from .models import Departamento

class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamento/lista.html"
    context_object_name = "departamentos"


class NewDepartamentoView(FormView):
    template_name = 'departamento/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'

    def form_valid(self, form):
        #import pdb; pdb.set_trace()
        print('****estamos en el form valid*****')

        depa = Departamento(
            name = form.cleaned_data['departamento'],
            shor_name = form.cleaned_data['shorname']
        )
        depa.save()

        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellido,
            job = '1',
            departamento = depa
        )
        return super().form_valid(form)
    

templates/departamento/lista.html
{% extends "base.html" %}



{% block title %}
    Lista departamentos
{% endblock title %}


{% block content %}
    {% include "includes/header.html" %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                        {% for departamento in departamentos %}
                            <tr>
                                <td>{{ departamento.name }}</td>
                                <td>{{ departamento.shor_name }}</td>
                                <td><a class="button warning" href="{% url "empleado_app:empleados_area" departamento.shor_name %}">Ver empleados</a></td>
                            </tr>
                        {% endfor %}
                        
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

templates/departamento/new_departamento.html
{% extends "base.html" %}


{% block title %}
Nuevo departamento
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class ="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar departamento</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres
                    {{ form.nombre}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos
                    {{ form.apellidos}}
            </div>
            <div class="medium-6 cell">
                <label>Departamento
                    {{ form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Shorname
                    {{ form.shorname}}
                </label>
            </div>
            <div class="medium-6 cell">
                <button type="submit" class="button success"> Añadir departamento </button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}