applications/empleados/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "empleado_app"

urlpatterns = [
    path(
        '',
        views.InicioView.as_view(),
        name='inicio'
        ),
    path(
        'listar-todo-empleados/', 
        views.ListAllEmpleados.as_view(),
        name='empleados_all'
        ),
    path('listar-by-area/<shorname>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'
        ),
    path('lista-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'
        ),
    path('listar-by-job/<job>/', views.ListByJobEmpleado.as_view()),
    path('buscar-empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar-habilidades-empleado/', views.ListHabilidadesEmpleado.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='detalle_empleado'),
    path('add-empleado/', 
        views.EmpleadoCreateView.as_view(),
        name='empleado_add'),
    path(
        'success/',
        views.SuccessView.as_view(),
        name='correcto'
        ),
    path(
        'update-empleado/<pk>/',
        views.EmpleadoUpdateView.as_view(),
        name='modificar_empleado'
        ),
    path(
        'delete-empleado/<pk>/',
        views.EmpleadoDeleteView.as_view(),
        name='eliminar_empleado'
        ),
]

empleado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.home.urls')),
    path('', include('applications.empleados.urls')),
    path('', include('applications.departamento.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/empleados/models.py
from django.db import models
from django.utils.translation import gettext as _
from ckeditor.fields import RichTextField

from applications.departamento.models import Departamento
# Create your models here.

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)
    
    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades empleados'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad 

class Empleado(models.Model):
    """Model para tabla empleado"""

    JOB_CHOICES = (
        ('0','CONTADOR'),
        ('1','ADMINISTRADOR'),
        ('2','ECONOMISTA'),
        ('3','OTRO'),
    )
    # contador
    # administrador
    # economista
    # otro
    first_name = models.CharField("Nombre", max_length=60)
    last_name = models.CharField("Apellidos", max_length=60)
    full_name = models.CharField('Nombres completos', max_length=120, blank=True)
    job = models.CharField("Trabajo", max_length=1, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Muchos empleados'
    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name + '-' + self.job 
    

applications/empleados/forms.py
from django import forms

from .models import Empleado

class EmpleadoForm(forms.ModelForm):
    
    class Meta:
        model = Empleado
        fields = (
            'first_name',
            'last_name',
            'job',
            'departamento',
            'image',
            'habilidades',
        )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/empleados/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)

#models
from .models import Empleado

#Formularios
from .forms import EmpleadoForm
# Create your views here.

class InicioView(TemplateView):
    template_name = 'inicio.html'

class ListAllEmpleados(ListView):
    template_name = 'empleado/list_all.html'
    paginate_by = 4
    ordering = 'first_name'
    #model = Empleado
    context_object_name = 'empleados'
    def get_queryset(self):
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            full_name__icontains = palabra_clave
        )
        return lista


class ListaEmpleadosAdmin(ListView):
    template_name = 'empleado/lista_empleados.html'
    paginate_by = 10
    ordering = 'first_name'
    context_object_name = 'empleados'
    model = Empleado
    

class ListByAreaEmpleado(ListView):
    template_name = 'empleado/list_by_area.html'
    context_object_name = 'empleados'
    """queryset = Empleado.objects.filter(
        departamento__shor_name = 'Contabilidad'
    )"""

    def get_queryset(self):
        area = self.kwargs['shorname']
        lista = Empleado.objects.filter(
        departamento__shor_name = area
        )
        return lista


class ListByJobEmpleado(ListView):
    template_name = 'empleado/list_by_job.html'
    def get_queryset(self):
        empleo = self.kwargs['job']
        lista = Empleado.objects.filter(
            job = empleo
        )
        print(empleo)
        return lista
    

class ListEmpleadosByKword(ListView):
    #lista empleado por palabra clave
    template_name = 'empleado/by_kword.html'
    context_object_name = 'empleado'

    def get_queryset(self):
        print('**************')
        palabra_clave = self.request.GET.get("kword", '')
        lista = Empleado.objects.filter(
            first_name = palabra_clave
        )
        return lista


class ListHabilidadesEmpleado(ListView):
    template_name = 'empleado/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        empleado = Empleado.objects.get(
            id = 1
        )
        return empleado.habilidades.all()
    

class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = "empleado/detail_empleado.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["titulo"] = "Empleado del mes"
        return context

class SuccessView(TemplateView):
    template_name = "empleado/success.html"


class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = "empleado/add.html"
    #fields = ['first_name','last_name','job']
    """fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
        'image'
    ]"""
    form_class= EmpleadoForm
    success_url = reverse_lazy('empleado_app:empleados_admin')

    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)

class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = "empleado/update.html"
    fields = [
        'first_name',
        'last_name',
        'job',
        'departamento',
        'habilidades',
    ]
    success_url = reverse_lazy('empleado_app:empleados_admin')

    def post(self, request, *args, **kwargs):
        print('*******Metodo POST*******')
        print('**************')
        print(request.POST)
        print(request.POST['last_name'])
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        print('*******Form Valid*******')
        print('**************')
        return super(EmpleadoUpdateView, self).form_valid(form)
    
class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = "empleado/delete.html"
    success_url = reverse_lazy('empleado_app:empleados_admin')

templates/empleado/add.html
{% extends "base.html" %}


{% block title %}
    Registrar empleado
{% endblock title %}

{% block content %}


{% include "includes/header.html" %}

<div class ="grid-container">
    <div class="grid-x">
        <h1 class="cell">Registrar empleado</h1>
        <form class="cell grid-x grid-margin-x" method="POST" enctype="multipart/form-data"> {% csrf_token %}
            <div class="medium-6 cell">
                <label>Nombres
                    {{ form.first_name}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Apellidos
                    {{ form.last_name}}
            </div>
            <div class="medium-6 cell">
                <label>Trabajo
                    {{ form.job}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Departamento
                    {{ form.departamento}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Habilidades
                    {{ form.habilidades}}
                </label>
            </div>
            <div class="medium-6 cell">
                <label>Avatar
                    {{ form.image}}
                </label>
            </div>
            <div class="medium-6 cell">
                <button type="submit" class="button success"> Guardar </button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}


<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Añadir empleado </button>
</form>

templates/empleado/by_kword.html
<h1>Buscar empleados por palabra clave</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="ingrese nombre aquí">
    <button type="submit">Buscar</button>
</form>

<h3>Lista de resultadosa</h3>

<ul>
     {% for e in empleado %}
        <li>{{e}}</li>
     {% endfor %}
</ul>

templates/empleado/delete.html
{% extends "base.html" %}



{% block title %}
    Eliminar Empleado
{% endblock title %}


{% block content %}
{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell"> Eliminar empleado: {{ object.full_name }}</h1>

        <form class="cell" method="POST">{% csrf_token %}
            <div class="callout alert" data-closable>
                <h5>¿Desea eliminar este empleado?</h5>               
                <button type="submit" class="alert button">Confirmar</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/empleado/detail_empleado.html
{% extends "base.html" %}

{% load static %}

{% block title %}
    {{objetc.full_name}}
{% endblock title %}

{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x grid-margin-x align-center">
        <div class="cell large-4 card" style="width: 300px;">
            <div class="card-divider">
                {{empleado.get_job_display}}
            </div>
            {% if empleado.image%}
                <img src="{{empleado.image.url}}">
            {% else %}
                <img src="{% static 'img/img1.jpg' %}">
            {% endif %}
            <div class="card-section">
                <h4>{{ empleado.full_name }}</h4>
                <p>{{ empleado.first_name }}</p>
                <p>{{ empleado.last_name }}</p>
                <p>{{ empleado.departamento.shor_name }}</p>
                <p><span class="label">Habilidades:</span></p>
                <ul class="vertical menu">
                    {% for h in empleado.habilidades.all  %}
                    <li>{{ h.habilidad }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>




{% endblock %}

<!--<h1> Detalle empleado {{ titulo }} </h1>

{{ object }}

{{ empleado }}

<h3> Todos los datos</h3>

<p>{{empleado.first_name}}</p>
<p>{{empleado.last_name}}</p>
<p>{{empleado.job}}</p>
<p>{{empleado.departamento}}</p>
-->

templates/empleado/habilidades.html
<h1> Lista de habilidades </h1>

<ul>
    {% for h in habilidades %}
        <li> {{h}} </li>
    {% endfor %}
</ul>

templates/empleado/list_all.html
{% extends "base.html" %}



{% block content %}

{% include "includes/header.html" %}


<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="buscar empleado">
            </div>
            <div class="cell large-2">
                <button type="submit" class="submit success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados  %}
                        <tr>
                            <td>{{ e.id }}</td>
                            <td>{{ e.first_name }}</td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.departamento }}</td>
                            <td><a class="button warning" href=" {% url "empleado_app:detalle_empleado" e.id %}">Ver</a></td>
                        </tr>
                    {% endfor %}                  
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                                <a href="?page={{ page_obj.previous_page_number }}">Atrás</a>
                            </li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number %}
                            <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                        {% else %}
                            <li class="">
                                <a href="?page={{ pagina }}">{{ pagina }}</a>
                            </li>
                        {% endif %}
                        {% endfor %}
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
            
        </div>
    </div>
</div>


{% endblock content %}

templates/empleado/list_by_area.html
{% extends "base.html" %}


{% block title %}
    lista empleados por departamento
{% endblock title %}


{% block content %}
    {% include "includes/header.html" %}

    <div class="grid-container">
        <div class="grid-x">
            <div class="cell">
                Empleados por area:
            </div>
            <div class="cell">
                <table>
                    <thead>
                        <tr>
                            <th width="200">ID</th>
                            <th>NOMBRES</th>
                            <th width="150">APELLIDOS</th>
                            <th width="150">DEPARAMENTO</th>
                            <th width="150">ACCION</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for e in empleados  %}
                            <tr>
                                <td>{{ e.id }}</td>
                                <td>{{ e.first_name }}</td>
                                <td>{{ e.last_name }}</td>
                                <td>{{ e.departamento }}</td>
                                <td><a class="button warning" href=" {% url "empleado_app:detalle_empleado" e.id %}">Ver</a></td>
                            </tr>
                        {% endfor %}                  
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}
<h1>Listar todos los empleados</h1>

<ul>
    {% for e in object_list%}
        <li>{{e}}</li>
    {% endfor %}
</ul>

templates/empleado/list_by_job.html
<h1>Listar todos los empleados por trabajo</h1>

<ul>
    {% for e in object_list%}
        <li>{{e}}</li>
    {% endfor %}
</ul>

templates/empleado/lista_empleados.html
ext{% extends "base.html" %}



{% block content %}

{% include "includes/header.html" %}


<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARAMENTO</th>
                        <th width="150">ACCION</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in empleados  %}
                        <tr>
                            <td>{{ e.id }}</td>
                            <td>{{ e.first_name }}</td>
                            <td>{{ e.last_name }}</td>
                            <td>{{ e.departamento }}</td>
                            <td>
                                <a class="button success" href=" {% url "empleado_app:modificar_empleado" e.id %}">Editar</a>                                
                            </td>
                            <td>                              
                                <a class="button alert" href=" {% url "empleado_app:eliminar_empleado" e.id %}">Eliminar</a>
                            </td>
                        </tr>
                    {% endfor %}                  
                </tbody>
            </table>
        </div>

        <div class="cell">
            {% if is_paginated %}
                <nav aria-label="Pagination">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="pagination-previous">
                                <a href="?page={{ page_obj.previous_page_number }}">Atrás</a>
                            </li>
                        {% endif %}
                        
                        {% for pagina in paginator.page_range %}
                        {% if pagina == page_obj.number %}
                            <li class="current"><span class="show-for-sr">You're on page</span> {{ pagina }}</li>
                        {% else %}
                            <li class="">
                                <a href="?page={{ pagina }}">{{ pagina }}</a>
                            </li>
                        {% endif %}
                        {% endfor %}
                        
                        {% if page_obj.has_next %}
                            <li class="pagination-next">
                                <a href="?page={{ page_obj.next_page_number }}">Siguiente</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            {% endif %}
            
        </div>
    </div>
</div>


{% endblock content %}

templates/empleado/success.html
<h1>Página de éxito. Felicidades.</h1>

templates/empleado/update.html
{% extends "base.html" %}



{% block title %}
    Editar Empleado
{% endblock title %}


{% block content %}

{% include "includes/header.html" %}

<div class="grid-container">
    <div class="grid-x">
        <h1> Modificar datos del empleado</h1>
    </div>
    <div class="cell">
        <form class="grid-x grid-margin-x" method="POST"> {% csrf_token %}
            <div class="cell large-6">
                <label>Nombre
                    {{ form.first_name }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Apellidos
                    {{ form.last_name }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Trabajo
                    {{ form.job }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Departamento
                    {{ form.departamento }}
                </label>
            </div>
            <div class="cell large-6">
                <label>Habilidades
                    {{ form.habilidades }}
                </label>
            </div>
            <div class="cell">
                <button type="submit" class="submit success button">Actualizar</button>
            </div>
            
        </form>
    </div>
</div>


{% endblock content %}


<form method="POST"> {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Actualizar</button>
</form>